// Generated by Wrangler — extended manually for this project
interface Env {
  AI: Ai;
  INCIDENT_AGENT: DurableObjectNamespace;
  INCIDENT_MEMORY: DurableObjectNamespace;
  REMEDIATION_WORKFLOW: Workflow;
}
